swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /devices:
    get:
      operationId: devices.read_all
      tags:
        - Devices
      summary: Read the entire set of devices, sorted by manufacturer
      description: Read the entire set of devices, sorted by manufacturer
      responses:
        200:
          description: Successfully read devices set operation
          schema:
            type: array
            items:
              properties:
                device_id:
                  type: integer
                  description: Id of the device
                manufacturer:
                  type: string
                  description: Manufacturer
                model_num:
                  type: string
                  description: Model Number
                device_type:
                  type: string
                  description: Type of Device (MediaDevice, TV or SmartTV)
                device_config_id:
                  type: integer
                  description: Mapping to the Remote Config that corresponds to this remote
                timestamp:
                  type: string
                  description: Creation/Update timestamp of the device
    post:
      operationId: devices.create
      tags:
        - Devices
      summary: Create a device
      description: Create a new device
      parameters:
        - name: device
          in: body
          description: Device to create
          required: True
          schema:
            type: object
            properties:
              device_id:
                type: integer
                description: Id of the device
              manufacturer:
                type: string
                description: Manufacturer of device to create
              model_num:
                type: string
                description: Model Number of device to create
              device_type:
                type: string
                description: Type of Device (MediaDevice, TV or SmartTV)
              device_config_id:
                  type: integer
                  description: Mapping to the Remote Config that corresponds to this remote
      responses:
        201:
          description: Successfully created device
          schema:
            properties:
              device_id:
                type: integer
                description: Id of the device
              manufacturer:
                type: string
                description: Manufacturer of the device
              model_num:
                type: string
                description: Model Number of the device
              device_type:
                type: string
                description: Type of Device (MediaDevice, TV or SmartTV)
              device_config_id:
                type: integer
                description: Mapping to the Remote Config that corresponds to this remote
              timestamp:
                type: string
                description: Creation/Update timestamp of the device record

  /devices/{device_id}:
    get:
      operationId: devices.read_one
      tags:
        - Devices
      summary: Read one device
      description: Read one device
      parameters:
        - name: device_id
          in: path
          description: Id of the device to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read device from devices data operation
          schema:
            type: object
            properties:
              device_id:
                type: integer
                description: Id of the device
              manufacturer:
                type: string
                description: Manufacturer of the device
              model_num:
                type: string
                description: Model Number of the device
              device_type:
                type: string
                description: Type of Device (MediaDevice, TV or SmartTV)
              device_config_id:
                type: integer
                description: Mapping to the Remote Config that corresponds to this remote
              timestamp:
                type: string
                description: Creation/Update timestamp of the device record

    put:
      operationId: devices.update
      tags:
        - Devices
      summary: Update a device
      description: Update a device
      parameters:
        - name: device_id
          in: path
          description: Id the device to update
          type: integer
          required: True
        - name: device
          in: body
          schema:
            type: object
            properties:
              manufacturer:
                type: string
                description: Manufacturer of the device
              model_num:
                type: string
                description: Model Number of the device
              device_type:
                type: string
                description: Type of Device (MediaDevice, TV or SmartTV)
              device_config_id:
                type: integer
                description: Mapping to the Remote Config that corresponds to this remote
      responses:
        200:
          description: Successfully updated device
          schema:
            properties:
              device_id:
                type: integer
                description: Id of the device in the database
              manufacturer:
                  type: string
                  description: Manufacturer of the device
              model_num:
                  type: string
                  description: Model Number of the device
              device_type:
                  type: string
                  description: Type of Device (MediaDevice, TV or SmartTV)
              device_config_id:
                  type: integer
                  description: Mapping to the Remote Config that corresponds to this remote
              timestamp:
                type: string
                description: Creation/Update timestamp of the device record

    delete:
      operationId: devices.delete
      tags:
        - Devices
      summary: Delete a device from the devices list
      description: Delete a device
      parameters:
        - name: device_id
          in: path
          type: integer
          description: Id of the device to delete
          required: true
      responses:
        200:
          description: Successfully deleted a device

  /device_configs:
    get:
      operationId: device_configs.read_all
      tags:
        - device_configs
      summary: Read the entire set of device configurations, sorted by manufacturer
      description: Read the entire set of devic configurationss, sorted by manufacturer
      responses:
        200:
          description: Successfully read device configurations set operation
          schema:
            type: array
            items:
              properties:
                device_config_id:
                  type: integer
                  description: Id of the device config
                device_config_name:
                  type: string
                  description: Description of Configuration
                timestamp:
                  type: string
                  description: Creation/Update timestamp of the device config
    post:
      operationId: device_configs.create
      tags:
        - device_configs
      summary: Create a device configuration
      description: Create a new device configuration
      parameters:
        - name: device configuration
          in: body
          description: Device configuration to create
          required: True
          schema:
            type: object
            properties:
              device_config_name:
                type: string
                description: name of Device Configuration to create
      responses:
        201:
          description: Successfully created device config
          schema:
            properties:
              device_config_id:
                type: integer
                description: Device Configuration Id of the device
              device_config_name:
                type: string
                description: Name of Device Configuration
              timestamp:
                type: string
                description: Creation/Update timestamp of the device config record

  /device_configs/{device_config_id}:
    get:
      operationId: device_configs.read_one
      tags:
        - device_configs
      summary: Read one device config
      description: Read one device config
      parameters:
        - name: device_config_id
          in: path
          description: Id of the device configuration to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read device config from device configs data operation
          schema:
            type: object
            properties:
              device_config_id:
                type: string
                description: Id of the device config
              device_config_name:
                type: string
                description: Name of the device config
              timestamp:
                type: string
                description: Creation/Update timestamp of the device config record

    put:
      operationId: device_configs.update
      tags:
        - device_configs
      summary: Update a device configuration
      description: Update a device configuration
      parameters:
        - name: device_config_id
          in: path
          description: Id the device config to update
          type: integer
          required: True
        - name: device_config
          in: body
          schema:
            type: object
            properties:
              device_config_name:
                type: string
                description: Name of the device configuration
      responses:
        200:
          description: Successfully updated device
          schema:
            properties:
              device_config_id:
                type: integer
                description: Id of the device config in the database
              device_config_name:
                  type: string
                  description: Name of the device configuration
              timestamp:
                type: string
                description: Creation/Update timestamp of the device config record

    delete:
      operationId: device_configs.delete
      tags:
        - Devices
      summary: Delete a device config from the device_configs list
      description: Delete a device_config
      parameters:
        - name: device_config_id
          in: path
          type: integer
          description: Id of the device config to delete
          required: true
      responses:
        200:
          description: Successfully deleted a device config
  /rc_buttons:
    get:
      operationId: rc_buttons.read_all
      tags:
        - rc_buttons
      summary: Read the entire set of rc_buttons
      description: Read the entire set of rc_buttons
      responses:
        200:
          description: Successfully read rc_buttons set operation
          schema:
            type: array
            items:
              properties:
                rc_button_id:
                  type: integer
                  description: Id of the RC button
                device_config_id:
                  type: integer
                  description: Id of the device config
                rc_type:
                  type: string
                  description: Type of remote control button
                rc_ir_code:
                  type: string
                  description: RC pronto hex code for button
                timestamp:
                  type: string
                  description: Creation/Update timestamp of the device config
    post:
      operationId: rc_buttons.create
      tags:
        - rc_buttons
      summary: Create a rc button configuration
      description: Create a new rc button configuration
      parameters:
        - name: rc button configuration
          in: body
          description: RC Button to create
          required: True
          schema:
            type: object
            properties:
              device_config_id:
                type: integer
                description: Id of the device config
              rc_type:
                type: string
                description: Type of remote control button
              rc_ir_code:
                type: string
                description: RC pronto hex code for button
              timestamp:
                type: string
                description: Timestamp of creation
      responses:
        201:
          description: Successfully created device config
          schema:
            properties:
              rc_button_id:
                type: integer
                description: Id of the rc_button
              device_config_id:
                  type: integer
                  description: Id of the device config
              rc_type:
                  type: string
                  description: Type of remote control button
              rc_ir_code:
                  type: string
                  description: RC pronto hex code for button
              timestamp:
                type: string
                description: Creation/Update timestamp of the device config record

  /rc_buttons/{rc_button_id}:
    get:
      operationId: rc_buttons.read_one
      tags:
        - rc_buttons
      summary: Read one rc_buttons config
      description: Read one rc_buttons config
      parameters:
        - name: rc_button_id
          in: path
          description: Id of the rc_buttons to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read device config from device configs data operation
          schema:
            type: object
            properties:
              rc_button_id:
                type: integer
                description: Id of the rc_button
              device_config_id:
                  type: integer
                  description: Id of the device config
              rc_type:
                  type: string
                  description: Type of remote control button
              rc_ir_code:
                  type: string
                  description: RC pronto hex code for button
              timestamp:
                type: string
                description: Creation/Update timestamp of the rc_button record
    put:
      operationId: rc_buttons.update
      tags:
        - rc_buttons
      summary: Update a rc_button configuration
      description: Update a rc_button configuration
      parameters:
        - name: rc_button_id
          in: path
          description: Id the rc_button to update
          type: integer
          required: True
        - name: rc_button
          in: body
          schema:
            type: object
            properties:
              device_config_name:
                type: string
                description: Name of the rc_button configuration
      responses:
        200:
          description: Successfully updated rc_button
          schema:
            properties:
              rc_button_id:
                type: integer
                description: Id of the rc_button
              device_config_id:
                  type: integer
                  description: Id of the device config
              rc_type:
                  type: string
                  description: Type of remote control button
              rc_ir_code:
                  type: string
                  description: RC pronto hex code for button
              timestamp:
                type: string
                description: Creation/Update timestamp of the rc_button record
    delete:
      operationId: rc_buttons.delete
      tags:
        - rc_buttons
      summary: Delete a rc_button from the rc_buttons list
      description: Delete a rc_button
      parameters:
        - name: rc_button_id
          in: path
          type: integer
          description: Id of the rc_button to delete
          required: true
      responses:
        200:
          description: Successfully deleted a rc_button
